---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install additional packages
  apt:
    name:
      - docker.io
      - php-fpm
      - php-cli
      - php-common
      - php-mysql
      - php-mbstring
      - php-xml
      - php-zip
      - php-gd
      - php-ftp
      - zlib1g-dev
    state: present
    install_recommends: yes
