---
- name: Update MOTD for all instances
  hosts: all
  become: yes
  tasks:
    - name: Update MOTD with instance information
      copy:
        content: |
          ================================================
          FastAPI Infrastructure - {{ instance_group | upper }} Instance
          ================================================
          Instance: {{ inventory_hostname }}
          Group: {{ instance_group }}
          Managed by: Ansible
          Last updated: {{ ansible_date_time.iso8601 }}
          ================================================
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

- name: Install MySQL client on FastAPI instances
  hosts: fastapi
  become: yes
  tasks:
    - name: Update package cache
      yum:
        update_cache: yes

    - name: Install MariaDB client (MySQL compatible)
      yum:
        name: mariadb1011
        state: present

    - name: Install additional useful tools
      yum:
        name:
          - htop
          - vim
          - wget
          - jq
          - awscli
        state: present

    - name: Install Python3 and pip
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install boto3 for AWS integration
      pip:
        name: boto3
        state: present
