services:
  teasel.auth0.provider:
    class: teasel\auth0\service\provider
    arguments:
      - '@config'
      - '@request'
    tags:
      - { name: auth.provider.oauth.service }
  teasel.auth0map.subscriber:
    class: teasel\auth0\event\subscriber
    arguments:
      - '@dbal.conn'
      - '@user'
    tags: 
      - { name: event.subscriber }
