---
all:
  children:
    fastapi:
      hosts:
        bastion:
          ansible_host: 3.9.71.10
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/fastapi-bastion.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        webserver:
          ansible_host: 10.0.10.132
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/fastapi-bastion.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/fastapi-bastion.pem ec2-user@3.9.71.10"'
      vars:
        ansible_python_interpreter: /usr/bin/python3
        instance_group: fastapi

    bastions:
      hosts:
        bastion:
          ansible_host: 3.9.71.10
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/fastapi-bastion.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      vars:
        ansible_python_interpreter: /usr/bin/python3
        instance_group: bastion

    webservers:
      hosts:
        webserver:
          ansible_host: 10.0.10.132
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/fastapi-bastion.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/fastapi-bastion.pem ec2-user@3.9.71.10"'
      vars:
        ansible_python_interpreter: /usr/bin/python3
        instance_group: webserver
