name: Forum Docker Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'forum/**'
      - '.github/workflows/forum-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'forum/**'
      - '.github/workflows/forum-build.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/forum

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Only build on push to develop or main, not on PRs
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Compute build metadata
      id: build_meta
      run: |
        echo "sha7=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        echo "utc=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

    - name: Build and push Forum Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./forum
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          GIT_SHA=${{ steps.build_meta.outputs.sha7 }}
          BUILD_TIME=${{ steps.build_meta.outputs.utc }}
